name: Release Creation

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Build production
        run: npm run build

      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: "dist/module.json"
        env:
          version: ${{steps.get_version.outputs.version}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{steps.get_version.outputs.version}}/wwn-random-contract-manager.zip

      - name: Zip files
        working-directory: ./dist
        run: zip -r ./wwn-random-contract-manager.zip ./*

      - name: Create versioned release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./dist/module.json, ./dist/wwn-random-contract-manager.zip"
          body: "Automated release for ${{ steps.get_version.outputs.version }}"
          draft: false
          generateReleaseNotes: true
          name: ${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
